export const styles = {
  title: {
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "24px",
    color: "#0F172A",
    paddingBottom: "40px",
  },
  th: {
    border: "none",
    textAlign: "start",
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "24px",
    alignItems: "center",
    color: "#94A3B8",
    padding: "8px 0",
  },
  td: {
    border: "none",
    textAlign: "start",
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "24px",
    alignItems: "center",
    color: "#0F172A",
    padding: "8px 0",
  },
};
